<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ESP32 OTA Publisher</title>
  <style>
    body { font-family: system-ui, sans-serif; background: #f2f6fb; color: #162033; margin: 0; }
    main { max-width: 560px; background: #fff; margin: 9vh auto; padding: 28px; border-radius: 16px; box-shadow: 0 8px 30px #b9c4d533; }
    label, input, button { display: block; width: 100%; box-sizing: border-box; }
    label { margin: 16px 0 6px; font-weight: 600; }
    input { padding: 11px; border: 1px solid #b9c4d5; border-radius: 8px; }
    button { margin-top: 22px; padding: 12px; border: 0; border-radius: 8px; background: #1769e0; color: #fff; font-weight: 700; }
    pre { white-space: pre-wrap; padding: 14px; min-height: 48px; background: #edf3fc; border-radius: 8px; }
    .hint { color: #596579; font-size: .9rem; }
  </style>
</head>
<body>
  <main>
    <h1>ESP32 OTA Publisher</h1>
    <p class="hint">Upload the <code>firmware.bin</code> generated by PlatformIO. Publishing a new version makes it available to connected ESP32 devices.</p>
    <form id="uploadForm">
      <label for="version">Firmware version</label>
      <input id="version" name="version" placeholder="1.0.1" required pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,63}">
      <label for="firmware">Firmware (.bin)</label>
      <input id="firmware" name="firmware" type="file" accept=".bin,application/octet-stream" required>
      <label for="ota_key">Administrator key</label>
      <input id="ota_key" name="ota_key" type="password" required>
      <button>Publish firmware</button>
    </form>
    <pre id="result">Select a firmware file to begin.</pre>
  </main>
  <script>
    document.getElementById('uploadForm').addEventListener('submit', async event => {
      event.preventDefault();
      const result = document.getElementById('result');
      result.textContent = 'Uploading...';
      try {
        const response = await fetch('api/upload.php', { method: 'POST', body: new FormData(event.currentTarget) });
        const data = await response.json();
        if (!response.ok || !data.success) throw new Error(data.message || `HTTP ${response.status}`);
        result.textContent = `Published version ${data.firmware.version}\nFile: ${data.firmware.filename}\nSHA-256: ${data.firmware.sha256}`;
      } catch (error) {
        result.textContent = `Error: ${error.message}`;
      }
    });
  </script>
</body>
</html>
